server:
  port: 9090

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/tacoCloud
    username: root
    password: wjy190206
    driver-class-name: com.mysql.jdbc.Driver
    schema: classpath:schema.sql
    data: classpath:data.sql
    initialization-mode: always

logging:
  config: G:/1_wjy/2023/Code/tacoCloud/src/main/resources/log4j.properties